### PR TITLE
Adapt to a new version of Lens

### LINKED ISSUE #75: Adapt to a new version of Lens
The Lens server has seen gradual improvements that require making adaptations
to the Addon.  The cloud service supports organizations, multiple workspaces
per user and directories within workspaces.

The addon should reflect that.

### PR DESCRIPTION
**Pull request by pieterhijma**
As discussed in issue #75, the addon supports multiple workspaces per user from potentially different organizations.  This pull requests provides a large update on the addon to align functionality with the Lens cloud service.

A summary of the new features:
- Support for multiple workspaces
- Workspaces can originate from different organizations
- The workspaces allow an offline workflow
- Directories are supported
- Workspaces can be used to collaborate within organizations
- The addon allows switching between versions and making versions active

Closes #75.

### CODE REVIEW

**Comment by pieterhijma** [comment]
@sliptonic and @prokoudine, please take a look at the README, the changelog, and package.xml. If time allows, perhaps a check of the code can be performed as well, for example by @PaddleStroke. However, the code has changed much.

The README has to be still updated with new images.

**Comment by sliptonic** [comment]
The debug level is debug.  On a run-through, I saw that it was echoing user credentials including password to the console.

**Comment by pieterhijma** [comment]
Yes, you're right, the credentials has already been fixed. The debug level should become INFO, but I left it on for now for the review.

**Comment by pieterhijma** [comment]
Pending other remarks, two things still have to be done:
- Setting `DEBUG_LEVEL` to `logging.INFO` in `Utils.py`
- Change screenshots in the README

**Comment by sliptonic** [comment]
I've changed the debug level.  I can't figure out how to change the screenshot images yet.  The readme source looks like the images are coming from the repo itself but they're not there and I don't think we want to include them anyway.
I'm merging and will figure out the readme images in a separate PR

**Pull request merged**
