### PR TITLE
Fix issue #18

### PR DESCRIPTION
**Pull request by PaddleStroke**

### CODE REVIEW

**Comment by PaddleStroke** [comment]
@AjinkyaDahale do you perhaps have some time to review this PR and also PR #23 ?
I prefer if they merged sooner rather than later to avoid conflicts, so as Brad is out I thought maybe you could check them?

**Review by amrit3701 — APPROVED** [review]
I am approving this PR, but variable names, method names should always be in `snake_case`.

**Comment by AjinkyaDahale** [comment]
> @AjinkyaDahale do you perhaps have some time to review this PR and also PR #23 ? I prefer if they merged sooner rather than later to avoid conflicts, so as Brad is out I thought maybe you could check them?

Was just looking at the PR when Amrit approved. I'm not involved in this code. Did you need an approval as a formality or a detailed look into the code?



> I am approving this PR, but variable names, method names should always be in `snake_case`.

Thanks for pointing it out! Seems the code is already `camelCase` so for consistency we should keep it and in a different PR make everything snake case if necessary.

**Comment by PaddleStroke** [comment]
Thanks!
Regarding snake_case vs camelCase, I initially wrote the addon in camelCase by habit as most of fc cpp is like this. I think some variable names are with snake_case when chatGPT was involved

**Pull request merged**
